version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/home/setwin/app
    ports:
      - "8009:80"
    command: ["-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
