version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/code/app
    ports:
      - "8000:80"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
